### PR TITLE
Lax qunitjs version from "1.10.0" to "^1.10.0"

### LINKED ISSUE #117: Allow users to specify qunitjs version
Under npm 1.x it loads qunitjs 1.10.0 which is quite old at this point.

Projects like karma-qunit specify a minimum version, thus allowing the final consumer to specify a different version in their package.json. https://github.com/karma-runner/karma-qunit/blob/v0.1.4/package.json:
```json
  "peerDependencies": {
    "qunitjs": "^1.14.0"
  },
```

Under npm 2.x it interestingly refuses to load 1.10.0 alongside a newer version in some cases, resutling in the following:
```
npm WARN unmet dependency qunit requires qunitjs@'1.10.0' but will load qunitjs, which is version 1.17.1
```

.. on a project with:
```json
  "devDependencies": {
    "karma": "0.12.31",
    "karma-qunit": "0.1.4",
    "qunit": "0.7.5",
    "qunitjs": "1.17.1"
```

### PR DESCRIPTION
**Pull request by Krinkle**
Fixes #117

### CODE REVIEW

**Comment by kof** [comment]
hmm why does it breaks travis?

**Comment by Krinkle** [comment]
I can reproduce the error locally.
```
  throw new assert.AssertionError({
        ^
AssertionError: no errors
    at /home/travis/build/kof/node-qunit/test/testrunner.js:49:11
    at /home/travis/build/kof/node-qunit/lib/testrunner.js:182:24
```

It seems the `assert` library is a bit useless when it comes to error reporting. Adding the following exposes the actual error:
```diff
diff --git a/test/testrunner.js b/test/testrunner.js
index fdb3eb0..221f9f7 100644
--- a/test/testrunner.js
+++ b/test/testrunner.js
@@ -46,6 +46,9 @@ chain.add('base testrunner', function() {
             failed: 2,
             passed: 5
         };
+        if (err) {
+            throw err;
+        }
         a.equal(err, null, 'no errors');
         a.ok(res.runtime > 0, 'Date was modified');
         delete res.runtime;
```
```
Error: Called start() outside of a test context too many times
    at Object.extend.start (node-qunit/node_modules/qunitjs/qunit/qunit.js:277:11)
    at _require (node-qunit/lib/child.js:66:11)
    at node-qunit/lib/child.js:177:5
    at Array.forEach (native)
    at Object.<anonymous> (node-qunit/lib/child.js:176:15)
```

**Comment by jzaefferer** [comment]
The stacktrace points at: https://github.com/kof/node-qunit/blob/master/lib/child.js#L66

That `_require()` method is called multiple times, so this looks like a bug in `node-qunit` that newer QUnit versions help to uncover.

**Comment by kof** [comment]
yeah QUnit.start(); is called multiple times, maybe in the older version it wasn't an issue ...

**Comment by JamesMGreene** [comment]
FYI, this behavior "tightening" arrived in `v1.16.0`. The previous behavior was considered a bug, so we did not honor its backward compatibility.

Discussion: https://github.com/jquery/qunit/pull/653#discussion_r17260617

**Comment by jzaefferer** [comment]
Which hopefully implies that the bug fix needed here **will** be backwards compatible.

**Comment by nikolas** [comment]
I ran into problems just trying to update node-qunit to QUnit v1.11.0: #110

**Comment by Krinkle** [comment]
Please fix this. Users are unable to use node-qunit with newer test suites because APIs introduced in the last 3 years of QUnit development (e.g. `assert.expect()`) fail on node-qunit which is pinned to QUnit 1.10.0 still.

**Comment by kof** [comment]
@Krinkle totally forgot this one, can we already update to an even newer version?

**Comment by jzaefferer** [comment]
1.20.0 was just released, but that shouldn't really matter, since the `^` includes all versions below 2.0.0.

**Comment by jzaefferer** [comment]
That said, you should definitely test with 1.20.0, since it might uncover other bugs in node-qunit. For example, calling `start()` with a non-numeric argument will cause tests to fail (somewhat similar to the other issue discussed above).

**Comment by kof** [comment]
@Krinkle would you like to  become a collaborator to this project?

**Comment by kof** [comment]
also @jzaefferer ?

**Comment by jzaefferer** [comment]
Sure, also @leobalter, since he's the (new) QUnit project lead.

**Comment by kof** [comment]
done

**Comment by kof** [comment]
welcome in team @jzaefferer @Krinkle @leobalter

**Comment by jzaefferer** [comment]
@kof thanks. So, are you going to put some time into fixing this or other issues, or are you hoping for one of us to take over?

**Comment by kof** [comment]
@jzaefferer I would be glad to get some help on this

**Comment by jzaefferer** [comment]
Okay. I've got some things to discuss with @leobalter anyway, maybe we can also do a triage of issues here.

**Comment by Krinkle** [comment]
Thanks @kof!

**Pull request closed without merging**
